### ISSUE TITLE
ERROR: please run connect() first

### ISSUE THREAD

**Issue by acromondx** [ncorbuk/Python---Email-Bomber#10]
I am getting this error even though I have enabled IMAP in my gmail account

"""
ERROR: please run connect() first
ERROR: please run connect() first
ERROR: please run connect() first
ERROR: please run connect() first
ERROR: please run connect() first
ERROR: please run connect() first
"""

Any solution

**Comment by Gccool** [comment]
2 things one I am having the same issue 2 how do I enable imap
